import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const spectral = localFont({
  src: [
    {
      path: '../public/fonts/Spectral-regular.woff2',
    },
  ],
  variable: '--font-spectral'
});

const DMSerif = localFont({
  src: [
    {
      path: '../public/fonts/DMSerifDisplay-Regular.woff2',
    },
  ],
  variable: '--font-DMSerif'
});

const DMSans = localFont({
  src: [
    {
      path: '../public/fonts/DMSans-9ptRegular.woff2',
    },
  ],
  variable: '--font-DMSans'
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spectral.variable} ${DMSerif.variable}  antialiased`}
      >

        {children}
      </body>
    </html>
  );
}
